minimum_pre_commit_version: "3.8.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --locked ruff check .
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        entry: uv run --locked ruff format --check .
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv run --locked mypy
        language: system
        pass_filenames: false
        types: [python]
